const fs = require("fs");
const process = require("child_process");
const packageJSON = JSON.parse(fs.readFileSync("./package.json"));
const readme = fs.readFileSync("README.md").toString().replace(/<https:\/\/github.com\/takumus\/ImagePetaPeta\/releases\/tag\/.*>/g, `<https://github.com/takumus/ImagePetaPeta/releases/tag/${packageJSON.version}>`);
fs.writeFileSync("README.md", readme);
console.log(process.execSync(`git add README.md`).toString());
console.log(process.execSync(`git add package.json`).toString());
console.log(process.execSync(`git commit -m "Update version ${packageJSON.version}"`).toString());
console.log("VERSION:", packageJSON.version);
console.log(process.execSync(`git tag ${packageJSON.version}`).toString());
console.log(process.execSync(`git push origin --tags`).toString());