export const IMG_TAG_WIDTH = 10000;
export const DEFAULT_BOARD_NAME = "noname";
export const SAVE_DELAY = 500;
export const CLICK_OFFSET = 20;
export const UNTAGGED_TAG_NAME = "Untagged";
export const DEFAULT_IMAGE_SIZE = 200;
export const PACKAGE_JSON_URL = "http://18.183.141.141/ImagePetaPeta/package.json";
export const DOWNLOAD_URL = "https://github.com/takumus/ImagePetaPeta/releases/tag/";
export const MAX_PREVIEW_COUNT = 100;
export const THUMBNAILS_SELECTION_PERCENT = 0.4;
export const BOARD_DEFAULT_BACKGROUND_FILL_COLOR = "#eeeeee";
export const BOARD_DEFAULT_BACKGROUND_LINE_COLOR = "#666666";
export const BOARD_DARK_BACKGROUND_FILL_COLOR = "#222222";
export const BOARD_DARK_BACKGROUND_LINE_COLOR = "#444444";
export const BOARD_MAX_PETAPANEL_COUNT = 100;
export const BOARD_MAX_PETAPANEL_ADD_COUNT = 20;
export const BOARD_ADD_MULTIPLE_OFFSET_X = 20;
export const BOARD_ADD_MULTIPLE_OFFSET_Y = 20;
export const BOARD_ZOOM_MIN = 1 / 100;     // 1%
export const BOARD_ZOOM_MAX = 5000 / 100; // 5000%
export const WINDOW_DEFAULT_WIDTH = 1280;
export const WINDOW_DEFAULT_HEIGHT = 720;
export const WINDOW_MIN_WIDTH = 640;
export const WINDOW_MIN_HEIGHT = 360;
export const BROWSER_THUMBNAIL_QUALITY = [60, 80, 100] as const;
export const BROWSER_THUMBNAIL_SIZE = [128, 256, 512, 1024] as const;
export const BROWSER_THUMBNAIL_ZOOM_MIN = 64;
export const BROWSER_THUMBNAIL_ZOOM_MAX = 512;
export const BROWSER_THUMBNAIL_ZOOM_STEP = 16;
export const UPDATE_CHECK_INTERVAL = 1000 * 60 * 60 * 1; // 1時間