name: CI

on:
  push:
    tags:
      # "vXX.XX.XX" で始まる Tag 名
      - "v*.*.*"

jobs:
  build_on_mac_arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: yarn install
        run: yarn install --network-timeout 600000
      - name: npm rebuild
        run: npm rebuild --platform=darwin --arch=arm64
      - name: yarn build
        run: yarn build:mac-arm64
      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          artifacts: |
            dist/electron/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_on_mac_intel:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: yarn install
        run: yarn install --network-timeout 600000
      - name: yarn build
        run: yarn build:mac-intel
      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          artifacts: |
            dist/electron/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: yarn install
        run: yarn install --network-timeout 600000
      - name: yarn build
        run: yarn build:win
      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          artifacts: |
            dist/electron/*.exe.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
