name: Release

on:
  push:
    branches:
      - main
    tags:
      # "vXX.XX.XX" で始まる Tag 名
      - "v*.*.*"

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: win
          - os: macos-12
            target: mac-arm64
          - os: macos-12
            target: mac-x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        id: build-cache_id
        env:
          cache-name: build-cache
        with:
          path: |
            node_modules
            .electron-builder-cache
          key: ${{ matrix.os }}-${{ matrix.target }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - run: echo '${{ toJSON(steps.build-cache_id.outputs) }}'
      - name: npm install
        run: npm install
      - name: build-vite
        run: npm run ci-build-vite
      - name: build-electron-${{ matrix.target }}
        run: npm run ci-build-electron:${{ matrix.target }}
      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          allowUpdates: true
          artifacts: |
            release/*.dmg,release/*.exe.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
