name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    strategy:
      matrix:
        include:
          # windows x64
          - os: windows-latest
            target: win
            artifacts: _release/*.exe.zip
          # mac arm64
          - os: [self-hosted, runner-01]
            target: mac-arm64
            artifacts: _release/*.dmg,_release/*.pkg
          # mac x64
          - os: [self-hosted, runner-02]
            target: mac-x64
            artifacts: _release/*.dmg,_release/*.pkg
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      # - uses: actions/cache@v3
      #   id: build-cache_id
      #   env:
      #     cache-name: build-cache
      #   with:
      #     path: |
      #       node_modules
      #       _electronBuilderCache
      #     key: ${{ matrix.os }}-${{ matrix.target }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - name: npm ci
        run: npm ci
      - name: audit
        run: npm audit --audit-level high
      - name: test
        run: npm run test
        env:
          CI: true
      - name: tsc
        run: npm run tsc
      - name: build vite
        run: npm run ci-build-vite
      - name: build electron (${{ matrix.target }})
        run: npm run ci-build-electron:${{ matrix.target }}
        env:
          WINDOWS_PFX: ${{ secrets.WINDOWS_PFX }}
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: ${{ matrix.artifacts }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
