name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
          # windows
          - os: windows-latest
          # mac
          - os: macos-latest
    if: ${{ !contains(github.event.pull_request.title, '[skip ci]') }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: npm ci
        run: npm ci
      - name: audit
        run: npm audit --audit-level high
      - name: test
        run: npm run test
        env:
          CI: true
      - name: tsc
        run: npm run tsc
