name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  release:
    strategy:
      matrix:
        include:
          # windows
          - os: windows-latest
          # mac
          - os: macos-ventura
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm install
        run: npm install
      - name: test
        run: npm run test
